# Generated by Django 4.0.3 on 2022-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fee', models.CharField(max_length=100)),
                ('exam', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
    ]
