# Generated by Django 4.0.3 on 2022-09-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='name',
            new_name='College_Name',
        ),
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='exam',
            new_name='Exam',
        ),
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='fee',
            new_name='Fee',
        ),
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='image',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='engineering_colleges',
            old_name='rating',
            new_name='Rating',
        ),
    ]
